name: release-draft

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  draft_release:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}